# Generated by Django 5.2.4 on 2025-08-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('company_name', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('company_phone_no', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=20)),
                ('company_address', models.TextField(blank=True)),
                ('login_email', models.EmailField(default='default@example.com', max_length=254)),
            ],
        ),
    ]
