# Generated by Django 5.2.4 on 2025-08-15 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('joining_date', models.DateField()),
                ('salary', models.PositiveIntegerField()),
                ('login_email', models.EmailField(default='default@example.com', max_length=254)),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_moved_to_completed', models.BooleanField(default=False)),
                ('total_checkpoints', models.PositiveIntegerField(default=0)),
                ('completed_checkpoints', models.PositiveIntegerField(default=0)),
                ('login_email', models.EmailField(default='default@example.com', max_length=254)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('login_email', models.EmailField(default='default@example.com', max_length=254)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='dashboard.task')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('login_email', models.EmailField(default='default@example.com', max_length=254)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_led', to='dashboard.employee')),
                ('members', models.ManyToManyField(related_name='teams', to='dashboard.employee')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.team'),
        ),
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('login_email', models.EmailField(default='default@example.com', max_length=254)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.team')),
            ],
        ),
    ]
