# Generated by Django 5.2.4 on 2025-07-08 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='performance',
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
