# Generated by Django 5.2.4 on 2025-08-15 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_client_task_expense_task_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='dashboard.task'),
        ),
    ]
