# Generated by Django 5.2.4 on 2025-08-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_client_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='project',
        ),
    ]
