# Generated by Django 5.2.4 on 2025-07-10 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('joining_date', models.DateField(default=datetime.date.today)),
                ('salary', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
