# Generated by Django 5.2.4 on 2025-07-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_employee_email_alter_employee_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
