# Generated by Django 5.2.4 on 2025-08-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_client_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('login_email', models.EmailField(default='default@example.com', max_length=254)),
            ],
        ),
    ]
