# Generated by Django 5.2.4 on 2025-08-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
