# Generated by Django 5.2.4 on 2025-07-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_employee_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
