# Generated by Django 5.2.4 on 2025-08-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_employee_salary_alter_task_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='login_email',
            field=models.EmailField(max_length=254),
        ),
    ]
