# Generated by Django 5.2.4 on 2025-08-16 05:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_budget_login_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30),
        ),
    ]
