# Generated by Django 5.2.4 on 2025-08-19 13:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_budget_total_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
