# Generated by Django 5.2.4 on 2025-08-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_checkpoints',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='total_checkpoints',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
