# Generated by Django 5.2.4 on 2025-08-14 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_task_completed_checkpoints_task_total_checkpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_moved_to_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('original_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completed_task', to='dashboard.task')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.team')),
            ],
        ),
    ]
