# Generated by Django 5.2.4 on 2025-08-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_task_is_moved_to_completed_completedtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtask',
            name='original_task',
        ),
    ]
